### ISSUE TITLE
Demande de Feature: permettre une utilisation simplifiée avec une CI pour un site statique

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_cli#284]
Pour permettre l'utilisation avec une CI (et éviter mon Workaround), il faudrait :
- pouvoir (comme LightHouse) renseigner un dossier de fichiers statiques htm(l), par défaut `--staticDistDir = ./public` ;
- pouvoir (comme LightHouse) limiter le nombre de fichiers mesurer, par défaut `--maxAutodiscoverUrls = 5` ;
- pouvoir (comme LightHouse) exclure une liste d'URL de pages à tester dans le serveur local, exemple `--autodiscoverUrlBlocklist = ["url1", "url2"]`.

> Cela induit d'avoir un serveur http dans le Dockerfile.

---
# Workaround GitLab
> En attendant, ma configuration avec mon runner GitLab.
>L'ulisation d'un docker-compose oblige d'avoir une configuration spéciale.

## Runner GitLab

```toml
concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "test-multi"
  url = "https://****"
  id = 49
  token = "*****"
  token_obtained_at = 2023-05-26T21:51:51Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
```
les paramètres importants:

```toml
privileged = true
volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
```

### docker-compose `.gitlab/docker-compose-ecoindex.yml`

Deux services :
- serveur http
- ecoindex-cli

```yml
version: "3"
services:
  http-server:
    image: busybox:latest
    command: ["/bin/busybox", "httpd", "-f", "-p", "8080"]
    working_dir: /public
    volumes:
      - ../public:/public
    networks:
      - test_ecoindex
    ports:
      - "8080:8080"
  ecoindex-cli:
    image: vvatelot/ecoindex-cli:latest
    volumes:
      - ../tmp/ecoindex-cli:/tmp/ecoindex-cli
    networks:
      - test_ecoindex
    depends_on:
      - http-server
    command: ecoindex-cli analyze --url http://http-server:8080 --recursive --html-report  --no-interaction --max-workers 1

networks:
  test_ecoindex:
```

### .gitlab-ci.yml

> Job spécifique.
- `GIT_STRATEGY: none` → Le dossier `.public` est créé dans un job précédent (.dependencies_cache) ;
- `<<: *rules_review` → La configuration écoutant les événements lançant le job ;
- `*git_branch_short` → Récupération de variables... ;
- `image: docker:20-dind` → Fonctionne **spécifiquement** avec cette version, sinon il y a des problèmes de network ;

```yml
Test Ecoindex:
  image: docker:20-dind
  <<: *rules_review
  variables:
    GIT_STRATEGY: none
  stage: test
  needs: ["Build"]
  extends: .dependencies_cache
  before_script:
    - *git_branch_short
    - docker info
    - docker-compose --version
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo "Test Ecoindex for branch $GIT_BRANCH_SHORT"
    - docker network create test_ecoindex
    - docker network ls
    - docker-compose -f .gitlab/docker-compose-ecoindex.yml down
    - docker-compose -f .gitlab/docker-compose-ecoindex.yml build
    - docker-compose -f .gitlab/docker-compose-ecoindex.yml up --abort-on-container-exit
  when: manual
```
